version: '3.8'

services:
  mysql-db:
    image: mysql
    restart: always
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reservation
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql