version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"